### ISSUE TITLE
Question about a feature 

### ISSUE THREAD

**Issue by wyredone** [cherysun/chatgpt-siri-shortcut#1]
I have built my own custom use prompts and would like to know if it’s possible to link to a specific shared chat or previously setup prompt. So for example say you setup a prompt that you loaded with a bunch of part numbers and prices - you could just say hey how much is #### and it would refer to the already built prompt list of data instructions and respond based on that. Is this possible?

**Comment by cherysun** [comment]
You can store your preset dataset as a structured file like JSON on your device, load it via Siri shortcut, and feed it to ChatGPT as parameters when calling the APIs. Note that using ChatGPT as an API doesn't give you access to your online session history, and you have to save the context locally on your own devices.
